### ISSUE TITLE
Add a blog section

### ISSUE THREAD

**Issue by tmigot** [jso-docs/jso-docs.github.io#19]
for instance we could write about the DCISolver.jl paper being accepted or the talk we gave at JuMP.
When publishing post on the Julia discourse we could redirect to blog posts written here.

**Comment by abelsiqueira** [comment]
We can rename this page: https://github.com/jso-docs/jso-docs.github.io/blob/main/tutorials.md
We can use something like "Post and tutorials". Then, if we have a few blog posts we can split them.
Or we can just start with them separated.

What do you think?

**Comment by tmigot** [comment]
As discussed in a separate meeting, a blog section is probably good!
I will send you a draft of a first article

**Comment by abelsiqueira** [comment]
Done.
